name = "dream_http_client"
version = "5.1.3"
description = "Type-safe HTTP client for Gleam with streaming support"
licences = ["MIT"]
repository = { type = "github", user = "TrustBound", repo = "dream" }
links = [
    { title = "Documentation", href = "https://hexdocs.pm/dream_http_client" },
    { title = "GitHub", href = "https://github.com/TrustBound/dream" },
]

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
gleam_erlang = ">= 1.1.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"

[erlang]
application_start_module = "dream_http_client_app"

[dev-dependencies]
dream = { path = "../.." }
dream_mock_server = { path = "../mock_server" }
gleeunit = ">= 1.0.0 and < 2.0.0"
mockth = { git = "https://github.com/bondiano/mockth.git", ref = "master" }
